name: Python CI
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing the project.
        run: |
          python -m pip install git+https://github.com/angeldollface/iconhelper
      - name: Trying to download a file.
        run: |
          python -m --source test/sample.png --platform MacOS && ls distMacOS